module.exports = {
    general: [
      {
        type: 'autogenerated',
        dirName: '.',
      },
      {
        type: 'link',
        label: 'News',
        href: 'https://vericoin.info/blog/',
      },
      {
        type: 'link',
        label: 'Videos',
        href: 'https://www.youtube.com/user/vericoinchannel',
      },
    ],
  };